#!/bin/bash
#set -e;

case "$1" in

  registry:login)
        shift
        echo "$@"       
        docker login "$@"
        ;;

  registry:push)
        mkdir -p /home/dokku/checkout
        cd /home/dokku/checkout
        UUID=$(uuidgen)
        git clone "$2" "$UUID"
        cd "$UUID"
        dokku create "$UUID"
        tar c . | dokku build "$UUID"
        docker tag "dokku/$UUID" "$3"
        docker push "$3"
        dokku delete "$UUID"
        rm -rf /home/dokku/checkout/"$UUID"
        ;;

  registry:pull)
        APP=$2
        DOCKER_REGISTRY_IMAGE=$3
        docker pull $DOCKER_REGISTRY_IMAGE
        #docker ps | grep "dokku/$APP" | awk '{print $1}' | xargs -r docker stop
        docker tag $DOCKER_REGISTRY_IMAGE "dokku/$APP"
        dokku release $APP
        dokku deploy $APP
        ;;

  help)

    cat && cat<<EOF
    registry:login                                  Perform a docker login ( all the remaining args are propagated )
    registry:push <git_url> <docker_registry_image> Clone a git url, exec buildstep and push the Docker image to the current registry
    registry:pull <app> <docker_registry_image>     Pull a buildstep built Docker image from the current registry and deploy
EOF
    ;;
esac